image: node:20

cache:
  paths:
    - node_modules/

stages:
  - build
  - deploy

build_job:
  stage: build
  script:
    - npm ci
    - npm run build:gitlab
  artifacts:
    paths:
      - build/
  only:
    - main

pages:
  stage: deploy
  script:
    - mkdir deploy
    - cp -r build/* deploy/
    - cp deploy/index.html deploy/404.html
  artifacts:
    paths:
      - deploy
  only:
    - main
