image: node:20

cache:
  paths:
    - node_modules/

stages:
  - build
  - deploy

build_job:
  stage: build
  script:
    - npm ci
    - npm run build:gitlab
  artifacts:
    paths:
      - build/
  only:
    - main

pages:
  stage: deploy
  script:
    - rm -rf public
    - mkdir public
    - cp -a build/. public/
    - cp public/index.html public/404.html
  artifacts:
    paths:
      - public
  only:
    - main
